### ISSUE TITLE
请问http代理要如何填写呢?

### ISSUE THREAD

**Issue by min704** [magicdmer/M3U8-Downloader#1]
我这样填写本地http代理 127.0.0.1:1080     提示格式错误. 希望看到能回复下,感谢了!~

**Comment by magicdmer** [comment]
> 我这样填写本地http代理 127.0.0.1:1080 提示格式错误. 希望看到能回复下,感谢了!~

加个http://，完整就是 http://127.0.0.1:1080

**Comment by min704** [comment]
> > 我这样填写本地http代理127.0.0.1:1080提示格式错误。希望看到能回复下，感谢了！〜
> 
> 加个HTTP：//，就是完整http://127.0.0.1:1080

好的, 多谢了!

**Comment by min704** [comment]
> > 我这样填写本地http代理127.0.0.1:1080提示格式错误。希望看到能回复下，感谢了！〜
> 
> 加个HTTP：//，就是完整http://127.0.0.1:1080

不知为何,我设置后没有走代理额,  同时的其他软件能正常走代理

**Comment by magicdmer** [comment]
> > > 我这样填写本地http代理127.0.0.1:1080提示格式错误。希望看到能回复下，感谢了！〜
> > 
> > 
> > 加个HTTP：//，就是完整http://127.0.0.1:1080
> 
> 不知为何,我设置后没有走代理额, 同时的其他软件能正常走代理

额，那我就不清楚了，因为最终是调用 ffmpeg的命令行来完成工作的，而不是这个界面程序

**Comment by fat00119** [comment]
确实设置了代理不走代理
