### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by xfdyd** [magicdmer/M3U8-Downloader#10]
软件简洁，十分难得。界面可以加宽一点，视频信息会覆盖“工具”菜单。
另外请问此软件支持多线程下载吗？

**Comment by magicdmer** [comment]
不好意思，我当初是需要用，就临时学习了一下c#语言，改了一下 nilaoda 的开源工程，然后之后就没用过了。所以我对  c# 语言其实是不熟悉的，另外由于不怎么用了，所以也没动力再去学习 c# 这些。你可以试试 https://github.com/nilaoda/N_m3u8DL-CLI 这个，或者去找个其他的 m3u8 下载器，很多的
