### ISSUE TITLE
可否批量下载支持自定义文件名？

### ISSUE THREAD

**Issue by leehow1988** [magicdmer/M3U8-Downloader#2]
可否批量下载支持自定义文件名？  看了下代码，是在这里：

`M3U8-Downloader/M3U8 Downloader/Form1.cs` 第398行的m_urlList是这样来的
```
m_urlList = Regex.Split(textBox_Adress.Text, Environment.NewLine, RegexOptions.IgnoreCase);
```
可否将 m_urlList 变成  m_urlList 和 m_nameList两个数组。由原来的单行只有下载路径
` http://xxxxxx.m3u8 `
变为单行里有下载路径而且有文件名
`xxx.mp4 http://xxxxxx.m3u8`

分别将文件名和下载路径装载进m_nameList和m_urlList两个数组。

这样第 404、408、518、522几行分别参照下面的改动将` textBox_Name.Text + m_count.ToString()` 改为 `m_nameList[m_count]`

如第518行改为
```
command = "-http_proxy " + m_proxy + " -rw_timeout 10000000 -i " + "\"" + m_urlList[m_count] + "\"" + " -c copy -y -bsf:a aac_adtstoasc -movflags +faststart " + "\"" + m_path + "\\" + textBox_Name.Text + m_count.ToString() + ".mp4" + "\"";
```
改成
```
command = "-http_proxy " + m_proxy + " -rw_timeout 10000000 -i " + "\"" + m_urlList[m_count] + "\"" + " -c copy -y -bsf:a aac_adtstoasc -movflags +faststart " + "\"" + m_path + "\\" + m_nameList[m_count] + ".mp4" + "\"";
```

**Comment by magicdmer** [comment]
你都贴代码了，就直接改了自己编译一下吧，我也是为了满足自身需求改了另一个开源工程

**Comment by leehow1988** [comment]
没想到这么快收到回复。 我这边还没接触过C#，本地编译环境啥的也没有（只有jdk环境）。我这个旧电脑都有可能折腾不起来，甚至打包也是一个很大的挑战。如果你电脑还能编译的话顺水推舟最好啦 ^_^ ，期待...

**Comment by magicdmer** [comment]
你这个需求很个人化，没法弄成通用的，批量下载的时候，一般人都和我一样，懒得一个个命名字，这样还不如下载后自己命名。

**Comment by leehow1988** [comment]
我还是觉得这个功能还是挺有必要。我只能自己想想办法了 ^_^，还是感谢你能开源这个工具 赞
