### ISSUE TITLE
问题分析

### ISSUE THREAD

**Issue by yonee77** [magicdmer/M3U8-Downloader#8]
班长，您好，可以帮忙分析一下为什么最新版工具下载这个地址，工具下载会卡在14%附近吗
https://live.video.weibocdn.com/4584535129858730_index.m3u8

**Comment by magicdmer** [comment]
其实问题不大，我试了一下，是可以下载完的，就是要等较长时间。然后你如果发现进度在增加，文件大小没变化，这时候其实可以终止了
